# Vector Operations: Scalar Multiplication, Sum and Dot Product of Vectors

In this lab you will use Python and `NumPy` functions to perform main vector operations: scalar multiplication, sum of vectors and their dot product. You will also investigate the speed of calculations using loop and vectorized forms of these main linear algebra operations

In [2]:
import numpy as np

## 1 - Scalar Multiplication and Sum of Vectors

### Scalar Multiplication

In [3]:
v = np.array([[2],[3]])

# Your code to multipy v with 2
v ** 2

array([[4],
       [9]])

### Sum of Vectors

In [4]:
v = np.array([[1],[3]])
w = np.array([[4],[-1]])

# Your code to sum w + v
sum(w+v)


array([7])

In [5]:
v + w

array([[5],
       [2]])

### Norm of a Vector

In [ ]:
# Your code to compute the norm of vecteor v

<a name='2'></a>
## 2 - Dot Product

### Dot Product using Python

In [ ]:
x = [1, -2, -5]
y = [4, 3, -1]

Next, let’s define a function `dot(x,y)` for the dot product calculation:

In [ ]:
# Your code to define the dot product


Now everything is ready to perform the dot product calculation calling the function `dot(x,y)`:

In [ ]:
print("The dot product of x and y is", dot(x, y))

Dot product is very a commonly used operator, so `NumPy` linear algebra package provides quick way to calculate it using function `np.dot()`:

In [ ]:
print("np.dot(x,y) function returns dot product of x and y:", np.dot(x, y)) 

Use `time.time()` function to evaluate amount of time (in seconds) required to calculate dot product using the function `dot(x,y)` which you defined above: 

In [ ]:
import time

a = np.random.rand(1000000)
b = np.random.rand(1000000)

tic = time.time()
c = dot(a,b)
toc = time.time()
print("Dot product: ", c)
print ("Time for the loop version: " + str(1000*(toc-tic)) + " ms")

Now compare it with the speed of the vectorized versions:

In [ ]:
tic = time.time()
c = np.dot(a,b)
toc = time.time()
print("Dot product: ", c)
print ("Time for the vectorized version, np.dot() function: " + str(1000*(toc-tic)) + " ms")

You can see that vectorization is extremely beneficial in terms of the speed of calculations!